version: '3.5'

services:
  database:
    container_name: database
    restart: on-failure
    image: postgres:alpine
    env_file: env/jorgechato.com/$ENV.env
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webapp

  backend:
    container_name: backend
    restart: on-failure
    # image: backend
    image: quay.io/orggue/jorgechato
    depends_on:
      - database
    env_file: env/jorgechato.com/$ENV.env
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    ports:
      - "8000:8000"
    networks:
      - webapp

  webserver:
    container_name: nginx
    image: quay.io/orggue/nginx-le
    depends_on:
      - database
      - backend
    env_file: env/jorgechato.com/$ENV.env
    volumes:
      - ./static:/static
      - ./media:/media
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
      - ./env/jorgechato.com/config/nginx/service.conf:/etc/nginx/service.conf
      - ./nginx/certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webapp


networks:
  webapp:
    name: webapp
