version: '3.5'

services:
  database:
    container_name: database
    restart: on-failure
    image: postgres:alpine
    env_file: env/jorgechato.com/$ENV.env
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webapp

  backend:
    container_name: backend
    restart: on-failure
    image: backend # quay.io/orggue/jorgechato
    depends_on:
      - database
    env_file: env/jorgechato.com/$ENV.env
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    ports:
      - "8000:8000"
    networks:
      - webapp

  webserver:
    container_name: nginx
    image: nginx:alpine
    env_file: env/jorgechato.com/$ENV.env
    depends_on:
      - database
      - backend
    volumes:
      - ./static:/static
      - ./media:/media
      - ./logs:/var/log/nginx
      - ./env/jorgechato.com/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./env/jorgechato.com/config/nginx/certs:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webapp


networks:
  webapp:
    name: webapp
